"use client";

import {useEffect} from "react";
import {useCarbonLanguage} from "./CarbonLanguageProvider";

type Locale = "en" | "ru";

const en: Record<string, string> = {
  "Azərbaycan": "Azerbaijan",
  "Bakı": "Baku",
  "Bakı, Azərbaycan": "Baku, Azerbaijan",
  "Ələsgər Qayıbov küç. 1222": "Alasgar Gayibov St. 12/22",
  "Ələsgər Qayıbov 12/22, Bakı": "Alasgar Gayibov 12/22, Baku",
  "Ana səhifə": "Home",
  "Avtomobillər": "Cars",
  "Toy avtomobilləri": "Wedding cars",
  "Haqqımızda": "About us",
  "Xidmətlər": "Services",
  "Əlaqə": "Contact",
  "Əlaqə saxla": "Contact us",
  "Bizimlə əlaqə": "Contact us",
  "Avtomobil seç": "Choose a car",
  "Avtomobil seçin": "Choose a car",
  "Bütün avtomobillər": "All cars",
  "Avtomobillərə bax": "View cars",
  "Kolleksiyaya bax": "View collection",
  "Kolleksiyanı araşdır": "Explore the collection",
  "Transfer avtomobilləri": "Transfer cars",
  "Transfer xidməti": "Transfer service",
  "Toy kolleksiyası": "Wedding collection",
  "Sifariş et": "Order",
  "Müraciət et": "Send request",
  "Sorğu ilə": "On request",
  "Sorğu": "Request",
  "Qiymət üçün əlaqə": "Contact for price",
  "/ gün": "/ day",
  "gün": "day",
  "GÜN": "DAYS",
  "nəfər": "people",
  "yer": "seats",
  "Hamısı": "All",
  "Filtrlər": "Filters",
  "Sıfırla": "Reset",
  "Təmizlə": "Clear",
  "Bağla": "Close",
  "Hazırdır": "Done",
  "Bu gün": "Today",
  "Tarix seçin": "Select date",
  "Seçilməyib": "Not selected",
  "Əvvəlki ay": "Previous month",
  "Növbəti ay": "Next month",
  "Götürülmə": "Pick-up",
  "Qaytarılma": "Return",
  "GÖTÜRMƏ": "PICK-UP",
  "QAYTARMA": "RETURN",
  "GÖTÜRMƏ TARİXİ": "PICK-UP DATE",
  "QAYTARMA TARİXİ": "RETURN DATE",
  "TƏHVİL": "HANDOVER",
  "Təhvil": "Handover",
  "Təhvil üsulu": "Handover method",
  "Carbon məntəqəsi": "Carbon office",
  "Ünvana çatdırılma": "Address delivery",
  "Çatdırılma": "Delivery",
  "Məntəqədən təhvil": "Pick up at office",
  "Sürücü": "Driver",
  "SÜRÜCÜ": "DRIVER",
  "Sürücü ilə": "With driver",
  "Sürücüsüz": "Self-drive",
  "Əlavə sürücü": "Additional driver",
  "Sürücü sayı": "Number of drivers",
  "SÜRÜCÜ SAYI": "DRIVER COUNT",
  "Əlavələr": "Extras",
  "ƏLAVƏ XİDMƏTLƏR": "EXTRA SERVICES",
  "ƏLAVƏ QEYD": "ADDITIONAL NOTE",
  "Prioritet dəstək": "Priority support",
  "Rezervasiya": "Reservation",
  "REZERVASİYA": "RESERVATION",
  "Rezervasiya et": "Reserve",
  "Sürətli rezervasiya": "Quick reservation",
  "SORĞU SİSTEMİ AKTİVDİR": "REQUEST SYSTEM ACTIVE",
  "Sistem aktivdir": "System active",
  "DAVAM ET": "CONTINUE",
  "Seçim edin": "Make a selection",
  "Nəticələri göstər": "Show results",
  "NƏTİCƏ": "RESULT",
  "uyğun nəticə": "matching results",
  "avtomobil göstərilir": "cars shown",
  "Uyğun avtomobil tapılmadı.": "No matching car found.",
  "Avtomobil tapılmadı": "Car not found",
  "Avtomobil tapılmadı.": "Car not found.",
  "Axtarışı dəyişin və ya aktiv filtrləri sıfırlayın.": "Change your search or reset active filters.",
  "Axtarışı və ya kateqoriyanı dəyişin.": "Change the search or category.",
  "Bütün avtomobilləri göstər": "Show all cars",
  "Səyahətinizə uyğun avtomobili tapın": "Find the car that fits your trip",
  "Avtomobili detallara görə seçin": "Choose a car by details",
  "ƏTRAFLI FİLTRLƏR": "DETAILED FILTERS",
  "İstehsalçı": "Manufacturer",
  "Sərnişin sayı": "Passenger count",
  "Çamadan tutumu": "Luggage capacity",
  "Kiçik baqaj tutumu": "Small luggage capacity",
  "Sürətlər qutusu": "Transmission",
  "Yanacaq növü": "Fuel type",
  "Mühərrik həcmi": "Engine size",
  "Ətraflı baxış": "View details",
  "seç və rezerv et": "select and reserve",
  "Carbon seçimi": "Carbon choice",
  "Əvvəl ucuz": "Lowest first",
  "Əvvəl premium": "Premium first",
  "Ada görə": "By name",
  "Əlaqə və": "Contact and",
  "dəstək.": "support.",
  "DƏSTƏK XƏTTİ AKTİVDİR": "SUPPORT LINE ACTIVE",
  "ƏLAQƏ KANALLARI": "CONTACT CHANNELS",
  "Birbaşa Carbon komandası": "Directly with the Carbon team",
  "Yazılı müraciətlər üçün": "For written requests",
  "ÜNVAN": "ADDRESS",
  "MÜRACİƏT MƏRKƏZİ": "REQUEST CENTER",
  "BİZƏ YAZIN": "WRITE TO US",
  "Nə barədə": "What would you like",
  "danışmaq istəyirsiniz?": "to talk about?",
  "Uyğun müraciət növünü seçin. Forma yalnız sizə lazım olan məlumatları göstərəcək.": "Choose the request type. The form will show only the information you need.",
  "Ümumi sorğu": "General inquiry",
  "Sualınız var?": "Have a question?",
  "İcarə, avtomobillər, rezervasiya və xidmətlər haqqında bizə yazın.": "Write to us about rental, cars, reservations and services.",
  "Şikayət": "Complaint",
  "Problem bildirin": "Report a problem",
  "Qarşılaşdığınız problemi ətraflı paylaşın. Hər müraciət diqqətlə araşdırılır.": "Share the issue in detail. Every request is reviewed carefully.",
  "Rəy": "Review",
  "Təcrübənizi bölüşün": "Share your experience",
  "Xidmət təcrübənizi bizimlə paylaşın və daha yaxşı olmağımıza kömək edin.": "Share your service experience and help us improve.",
  "SEÇİLİB": "SELECTED",
  "SEÇ": "SELECT",
  "Məlumatlarınız yalnız müraciətinizi cavablandırmaq məqsədilə istifadə olunur.": "Your information is used only to respond to your request.",
  "ÜMUMİ MÜRACİƏT": "GENERAL REQUEST",
  "ŞİKAYƏT FORMASI": "COMPLAINT FORM",
  "RƏY FORMASI": "REVIEW FORM",
  "Sualınızı bizə göndərin.": "Send us your question.",
  "Problemi bizə bildirin.": "Tell us about the issue.",
  "Təcrübənizi paylaşın.": "Share your experience.",
  "2 dəq.": "2 min.",
  "AD": "NAME",
  "SOYAD": "SURNAME",
  "Adınız": "Your name",
  "Soyadınız": "Your surname",
  "Adınız və soyadınız": "Your full name",
  "ƏLAQƏ NÖMRƏSİ": "CONTACT NUMBER",
  "MÖVZU": "TOPIC",
  "Mövzu": "Topic",
  "Müraciətin mövzusunu seçin": "Select the request topic",
  "Avtomobil seçimi": "Car selection",
  "Qiymət və depozit": "Price and deposit",
  "Sığorta": "Insurance",
  "Digər": "Other",
  "ŞİKAYƏTİNİZ NƏ İLƏ BAĞLIDIR?": "WHAT IS YOUR COMPLAINT ABOUT?",
  "Kateqoriya seçin": "Select a category",
  "Ödəniş / depozit": "Payment / deposit",
  "Əməkdaş / xidmət": "Employee / service",
  "Təhvil / qaytarılma": "Handover / return",
  "İCARƏ TARİXİ": "RENTAL DATE",
  "AVTOMOBİLİN MARKASI / MODELİ": "CAR BRAND / MODEL",
  "XİDMƏT GÖSTƏRƏN ƏMƏKDAŞ": "SERVICE EMPLOYEE",
  "Adı bilirsinizsə qeyd edin": "Enter the name if you know it",
  "RƏYİNİZ": "YOUR REVIEW",
  "ŞİKAYƏTİNİZ": "YOUR COMPLAINT",
  "MESAJINIZ": "YOUR MESSAGE",
  "Təcrübənizi bizimlə bölüşün...": "Share your experience with us...",
  "Qarşılaşdığınız vəziyyəti mümkün qədər ətraflı izah edin...": "Describe the situation in as much detail as possible...",
  "Sualınızı və ya müraciətinizi yazın...": "Write your question or request...",
  "Göndər düyməsi cihazınızda email tətbiqini müraciət məlumatları ilə açacaq.": "The send button will open your email app with the request details.",
  "Müraciəti hazırla": "Prepare request",
  "MÜRACİƏT HAZIRDIR": "REQUEST READY",
  "Emailiniz": "Your email",
  "hazırlanır.": "is being prepared.",
  "Email tətbiqiniz açıldıqda məlumatları yoxlayıb göndərə bilərsiniz.": "When your email app opens, you can review and send the details.",
  "MÜRACİƏT KODU": "REQUEST CODE",
  "Formaya qayıt": "Back to form",
  "Səfərdən əvvəl,": "Before the trip,",
  "səfər zamanı,": "during the trip,",
  "səfərdən sonra.": "after the trip.",
  "Məqsədimiz sadəcə avtomobil təqdim etmək deyil. Bütün icarə təcrübəsi boyunca sizin üçün əlçatan qalmaqdır.": "Our goal is not just to provide a car. We stay available throughout the entire rental experience.",
  "İndi zəng et": "Call now",
  "Məqalə": "Article",
  "MƏQALƏ": "ARTICLE",
  "Növbəti oxu.": "Next read.",
  "Bütün məqalələr": "All articles",
  "Yol üçün": "Better ideas",
  "daha yaxşı fikirlər.": "for the road.",
  "Avtomobil, səyahət, sığorta və düzgün seçim haqqında qısa, praktik bələdçilər.": "Short practical guides about cars, travel, insurance and choosing well.",
  "Kateqoriya": "Category",
  "Seçilmiş məqalə": "Featured article",
  "Son yazılar": "Latest posts",
  "Oxumağa başla": "Start reading",
  "Oxu": "Read",
  "Oxumaq kifayətdir.": "Read enough.",
  "İndi yola çıx.": "Now hit the road.",
  "Avtomobil kirayəsi, sığorta, səyahət marşrutları və avtomobil baxımı haqqında Carbon Rent A Car məqalələri.": "Carbon Rent A Car articles about car rental, insurance, travel routes and car care.",
  "Qiymət və Sığorta Maarifləndirməsi": "Price and Insurance Guide",
  "Ucuz avtomobil kirayəsi hər zaman sərfəlidirmi?": "Is cheap car rental always worth it?",
  "Kirayə Məsləhətləri": "Rental Tips",
  "Səyahət Marşrutları və Tövsiyələri": "Travel Routes and Recommendations",
  "Avtomobil Baxımı və Texniki Məlumatlar": "Car Care and Technical Information",
  "Niyə Carbon Rent A Car-ı Seçirlər?": "Why People Choose Carbon Rent A Car",
  "İcarə bələdçisi": "Rental guide",
  "Məsləhətlər": "Tips",
  "Səyahət": "Travel",
  "5 dəq": "5 min",
  "4 dəq": "4 min",
  "6 dəq": "6 min",
  "7 dəq": "7 min",
  "Haqqımızda | Carbon Rent A Car": "About Us | Carbon Rent A Car",
  "Carbon Rent A Car haqqında — müasir, etibarlı və premium avtomobil icarəsi xidməti.": "About Carbon Rent A Car - a modern, reliable and premium car rental service.",
  "Məmnun müştəri": "Happy customers",
  "İllik təcrübə": "Years of experience",
  "Premium avtomobil icarəyə verilib": "Premium cars rented",
  "Müştəri məmnuniyyəti": "Customer satisfaction",
  "Keyfiyyət": "Quality",
  "Saz, təmiz və premium standartlara uyğun avtomobillər.": "Clean, well-maintained cars that meet premium standards.",
  "Şəffaf şərtlər": "Transparent terms",
  "Aydın qiymətlər, aydın qaydalar və gizli sürprizlərsiz icarə prosesi.": "Clear prices, clear rules and a rental process without hidden surprises.",
  "Geniş avtomobil seçimi": "Wide car selection",
  "Texniki baxışdan keçmiş saz maşınlar": "Inspected, road-ready cars",
  "Yolunuzda yanınızdayıq": "With you on the road",
  "Etibar və xidmət": "Trust and service",
  "Carbon Rent A Car xidmət fəlsəfəsi.": "Carbon Rent A Car service philosophy.",
  "Müştəri təcrübəsinə necə yanaşdığımızı izləyin.": "See how we approach customer experience.",
  "Səsi aç": "Unmute",
  "Səsi bağla": "Mute",
  "Dayandır": "Pause",
  "Hava Limanı": "Airport",
  "Hava limanı": "Airport",
  "Gündəlik": "Daily",
  "Uzunmüddətli": "Long-term",
  "SUV və": "SUV and",
  "off-road icarəsi.": "off-road rental.",
  "Sərbəst": "Independent",
  "Həftəlik": "Weekly",
  "Aylıq": "Monthly",
  "Servis daxil": "Service included",
  "Tam sığorta": "Full insurance",
  "Tam sığortalı": "Fully insured",
  "Geniş seçim": "Wide choice",
  "Premium xidmət": "Premium service",
  "Bakı və regionlar": "Baku and regions",
  "Xidmətlərimiz | Carbon Rent A Car": "Our Services | Carbon Rent A Car",
  "Carbon Rent A Car xidmətləri — gündəlik və uzunmüddətli avtomobil icarəsi, hava limanı transferi, toy avtomobilləri, sürücüsüz icarə və SUV xidmətləri.": "Carbon Rent A Car services - daily and long-term car rental, airport transfers, wedding cars, self-drive rental and SUV services.",
  "Şərtlər və Qaydalar | Carbon Rent A Car": "Terms and Conditions | Carbon Rent A Car",
  "Məxfilik Siyasəti | Carbon Rent A Car": "Privacy Policy | Carbon Rent A Car",
  "Hüquqi məlumat": "Legal information",
  "Şərtlər və Qaydalar": "Terms and Conditions",
  "Ən son yeniləmə: 24 iyul 2025": "Last updated: July 24, 2025",
  "9 bölmə": "9 sections",
  "Giriş": "Introduction",
  "Rezervasiya Şərtləri": "Reservation Terms",
  "Ödəniş və Depozit Qaydaları": "Payment and Deposit Rules",
  "Təslim və Qaytarılma Qaydaları": "Handover and Return Rules",
  "Sığorta Şərtləri": "Insurance Terms",
  "İstifadə Məhdudiyyətləri": "Use Restrictions",
  "Texniki Problem Halları": "Technical Problem Cases",
  "Müştərinin Məsuliyyəti": "Customer Responsibility",
  "Şirkətin Hüquqları": "Company Rights",
  "Şərtlərlə bağlı sualınız var?": "Have a question about the terms?",
  "Carbon Rent A Car xidmətlərindən istifadə, rezervasiya, ödəniş, avtomobilin təhvil alınması və qaytarılması üçün tətbiq olunan əsas şərtlər.": "The main terms for using Carbon Rent A Car services, reservations, payments, vehicle handover and return.",
  "Carbon Rent A Car xidmətlərindən istifadə etməklə, aşağıda qeyd olunan şərtləri qəbul etmiş olursunuz.": "By using Carbon Rent A Car services, you accept the terms below.",
  "Bu şərtlər saytımız vasitəsilə edilən bütün rezervasiyalara və kirayə müqavilələrinə şamil olunur.": "These terms apply to all reservations and rental agreements made through our website.",
  "Avtomobil kirayə etmək üçün minimum yaş həddi 21 yaşdır.": "The minimum age for renting a car is 21.",
  "Müştərinin etibarlı sürücülük vəsiqəsi olmalıdır və minimum 1 il sürücülük təcrübəsi tələb olunur.": "The customer must have a valid driver's license and at least 1 year of driving experience.",
  "Rezervasiya zamanı düzgün şəxsi məlumatların təqdim edilməsi mütləqdir.": "Accurate personal information must be provided during reservation.",
  "Ödəniş nağd, kartla və ya online mümkündür.": "Payment is possible in cash, by card or online.",
  "Depozit məbləği avtomobilin sinfi, icarə müddəti, sürücülük təcrübəsi və digər amillər nəzərə alınmaqla təyin edilə və ya edilməyə bilər.": "The deposit amount may or may not be set depending on vehicle class, rental duration, driving experience and other factors.",
  "Depozit təyin olunubsa, götürülmüş depozit müqavilədə mütləq şəkildə öz əksini tapmalıdır.": "If a deposit is assigned, the collected deposit must be reflected in the agreement.",
  "Kirayə müddəti bitdikdən sonra avtomobil qaytarılarkən hər hansı cərimə və ya zərər olmadığı halda depozit tam şəkildə qaytarılır.": "After the rental period ends, the deposit is fully returned when the car is returned without fines or damage.",
  "Avtomobil razılaşdırılmış tarix və saatda təhvil verilir.": "The vehicle is handed over at the agreed date and time.",
  "Qaytarılma gecikərsə, əlavə ödəniş tətbiq oluna bilər.": "If return is delayed, an additional fee may apply.",
  "Avtomobil eyni yanacaq səviyyəsi ilə qaytarılmalıdır.": "The vehicle must be returned with the same fuel level.",
  "Bütün avtomobillər icbari və kasko sığorta ilə təmin olunub.": "All cars are covered by mandatory and comprehensive insurance.",
  "Qəza halında dərhal şirkət və DYP ilə əlaqə saxlanılmalıdır.": "In case of an accident, the company and traffic police must be contacted immediately.",
  "Avtomobilin üçüncü şəxslərə verilməsi qadağandır.": "It is forbidden to transfer the vehicle to third parties.",
  "Avtomobil yalnız Azərbaycan Respublikasının ərazisində istifadə oluna bilər.": "The vehicle may only be used within the territory of the Republic of Azerbaijan.",
  "Avtomobildən qanunsuz fəaliyyətlərdə və sürücülük qaydalarını pozan hallarda istifadə qəti qadağandır.": "Using the vehicle for illegal activities or in violation of driving rules is strictly prohibited.",
  "Avtomobilin nasazlığı zamanı dərhal bizimlə əlaqə saxlayın.": "Contact us immediately if the vehicle has a technical fault.",
  "Zərurət yarandıqda 24/7 texniki yardım və əvəz avtomobil təqdim olunur.": "If necessary, 24/7 technical assistance and a replacement car are provided.",
  "Müştəri avtomobilə vurduğu hər hansı zərəri kompensasiya etməklə məsuldur.": "The customer is responsible for compensating any damage caused to the vehicle.",
  "Avtomobilin salonunun təmiz saxlanılması və avtomobildən istismar qaydalarına uyğun istifadə edilməsi tələb olunur.": "The vehicle interior must be kept clean and the vehicle must be used according to operating rules.",
  "Şirkət zəruri hallarda — sənədlərin uyğun olmaması və ya təhlükəsizlik səbəbləri daxil olmaqla — sifarişi qəbul etməmək hüququna malikdir.": "The company reserves the right to refuse an order when necessary, including document mismatch or safety reasons.",
  "Şirkət bu şərtləri xəbərdarlıq etmədən dəyişdirmək hüququnu özündə saxlayır.": "The company reserves the right to change these terms without notice.",
  "Dəyişikliklər saytımızda elan olunduğu tarixdən qüvvəyə minir.": "Changes take effect from the date they are published on our website.",
  "Rezervasiya və ya kirayə şərtləri ilə bağlı əlavə məlumat üçün komandamızla əlaqə saxlaya bilərsiniz.": "For more information about reservation or rental terms, you can contact our team.",
  "Carbon Rent A Car komandası olaraq xidmətimizdən istifadə etdiyiniz üçün təşəkkür edirik və sizə rahat, təhlükəsiz səyahətlər arzulayırıq.": "As the Carbon Rent A Car team, thank you for using our service. We wish you comfortable and safe journeys.",
  "Məxfilik Siyasəti": "Privacy Policy",
  "10 bölmə": "10 sections",
  "Məxfilik üzrə əlaqə": "Privacy contact",
  "Toplanan Məlumatlar": "Information Collected",
  "Məlumatların Toplanma Yolları": "How Information Is Collected",
  "Məlumatların İstifadə Edilməsi": "Use of Information",
  "Məlumatların Paylaşılması": "Sharing Information",
  "Təhlükəsizlik": "Security",
  "Məlumatların Saxlanması Müddəti": "Data Retention Period",
  "İstifadəçi Hüquqları": "User Rights",
  "Cookies Siyasəti": "Cookie Policy",
  "Dəyişikliklər": "Changes",
  "Məlumatlarınızla bağlı sualınız var?": "Have a question about your data?",
  "Məxfilik Siyasətimiz şəxsi məlumatlarınızın necə toplanması, istifadəsi və qorunması barədə məlumat verir. Məxfiliyiniz və təhlükəsizliyiniz bizim üçün prioritetdir.": "Our Privacy Policy explains how your personal information is collected, used and protected. Your privacy and security are our priority.",
  "Carbon Rent A Car olaraq müştərilərimizin məxfiliyinə hörmətlə yanaşırıq və şəxsi məlumatlarınızın qorunmasına sadiqik.": "At Carbon Rent A Car, we respect our customers' privacy and are committed to protecting your personal information.",
  "Bu məxfilik siyasəti sizə hansı məlumatları topladığımızı, necə istifadə etdiyimizi və qoruduğumuzu izah edir.": "This privacy policy explains what information we collect, how we use it and how we protect it.",
  "Saytımız vasitəsilə aşağıdakı şəxsi məlumatları toplaya bilərik:": "We may collect the following personal information through our website:",
  "Ad və soyad": "Name and surname",
  "Telefon nömrəsi": "Phone number",
  "Email ünvanı": "Email address",
  "Rezervasiya tarixləri və avtomobil seçimi": "Reservation dates and car selection",
  "Ödəniş məlumatları — online ödəniş etdiyiniz halda": "Payment information, if you make an online payment",
  "İstifadəçi davranış məlumatları — cookies və analitika vasitəsilə": "User behavior data through cookies and analytics",
  "Topladığımız məlumatlar aşağıdakı məqsədlərlə istifadə edilir:": "The information we collect is used for the following purposes:",
  "Rezervasiyanızı təsdiqləmək və xidmət göstərmək": "To confirm your reservation and provide service",
  "Müştəri xidmətləri üçün əlaqə yaratmaq": "To contact you for customer service",
  "Təhlükəsizlik və fırıldaqçılığın qarşısını almaq": "To ensure security and prevent fraud",
  "Kampaniya və yeniliklər barədə məlumat göndərmək — yalnız razılığınız varsa": "To send campaign and update information only with your consent",
  "Saytın və xidmətlərimizin inkişafı üçün təhlil aparmaq": "To analyze and improve the website and our services",
  "Şəxsi məlumatlarınız üçüncü tərəflərlə paylaşılmır. Aşağıdakı hallar istisna təşkil edir:": "Your personal information is not shared with third parties, except in the following cases:",
  "Məlumatlarınızın qorunması üçün zəruri texniki və təşkilati təhlükəsizlik tədbirləri görülür.": "Necessary technical and organizational security measures are taken to protect your data.",
  "Rezervasiya və əlaqə məlumatları xidmət müddəti və qanunvericiliyə uyğun olaraq saxlanılır.": "Reservation and contact information is stored according to service needs and applicable law.",
  "Siz aşağıdakı hüquqlara maliksiniz:": "You have the following rights:",
  "Şəxsi məlumatlarınıza çıxış etmək": "Access your personal information",
  "Onları düzəltmək və ya yeniləmək": "Correct or update it",
  "Bu hüquqlarla bağlı müraciət etmək üçün bizimlə əlaqə saxlaya bilərsiniz.": "You can contact us to exercise these rights.",
  "Saytımız istifadəçi təcrübəsini yaxşılaşdırmaq üçün cookies istifadə edir. Cookies-i brauzerinizin ayarlarından idarə edə və ya silə bilərsiniz.": "Our website uses cookies to improve user experience. You can manage or delete cookies in your browser settings.",
  "Saytımızdan istifadə etməklə cookies siyasətimizə razılıq vermiş olursunuz.": "By using our website, you agree to our cookie policy.",
  "Məxfilik siyasətimiz zaman-zaman yenilənə bilər. Dəyişikliklər bu səhifədə yerləşdirilir və yenilənmə tarixi göstərilir.": "Our privacy policy may be updated from time to time. Changes are posted on this page with the update date.",
  "Siyasəti mütəmadi olaraq nəzərdən keçirməyiniz tövsiyə olunur.": "We recommend reviewing the policy regularly.",
  "Şəxsi məlumatlarınıza çıxış, düzəliş və ya məxfilik siyasəti ilə bağlı bizimlə əlaqə saxlaya bilərsiniz.": "You can contact us about access to your personal data, corrections or this privacy policy.",
  "Carbon Rent A Car komandası olaraq şəxsi məlumatlarınızın qorunmasına daim diqqət yetiririk. Bizi seçdiyiniz üçün təşəkkür edirik.": "As the Carbon Rent A Car team, we always pay attention to protecting your personal information. Thank you for choosing us.",
  "Toy Avtomobilləri | Carbon Rent A Car": "Wedding Cars | Carbon Rent A Car",
  "Toy, nişan və xüsusi günlər üçün premium avtomobillər. Carbon Rent A Car.": "Premium cars for weddings, engagements and special days. Carbon Rent A Car.",
  "XÜSUSİ GÜNLƏR ÜÇÜN": "FOR SPECIAL DAYS",
  "Qiymət": "Price",
  "/ başlayır": "/ starts from",
  "başlayır": "starts from",
  "Tarix üzrə rezervasiya": "Reservation by date",
  "Tədbir gününüzə uyğun planlama": "Planning around your event day",
  "Vaxtın dəqiqləşdirilməsi": "Time confirmation",
  "Komandamız sizinlə əvvəlcədən əlaqə saxlayır": "Our team contacts you in advance",
  "Xüsusi çəkiliş planını müraciətdə qeyd edin": "Mention the special shoot plan in your request",
  "Etibarlı xidmət": "Reliable service",
  "Carbon komandası tərəfindən təşkil olunur": "Organized by the Carbon team",
  "Tarix və detalları dəqiqləşdirin": "Confirm date and details",
  "XİDMƏT PROSESİ": "SERVICE PROCESS",
  "Sadə və": "Simple and",
  "aydın.": "clear.",
  "Avtomobili seçin": "Choose the car",
  "Tarixi bildirin": "Share the date",
  "Detalları razılaşdırın": "Agree on details",
  "Günün dadını çıxarın": "Enjoy the day",
  "Bilmək istədiyiniz": "Everything you want",
  "hər şey.": "to know.",
  "DİGƏR SEÇİMLƏR": "OTHER OPTIONS",
  "Digər toy avtomobilləri": "Other wedding cars",
  "Hamısına bax": "View all",
  "Xüsusi gününüz": "Your special day",
  "Carbon ilə.": "with Carbon.",
  "Rezervasiya linki natamamdır və ya avtomobil artıq mövcud deyil.": "The reservation link is incomplete or the car is no longer available.",
  "Avtomobillərə qayıt": "Back to cars",
  "Avtomobilə qayıt": "Back to car",
  "Səfər": "Trip",
  "Yoxlama": "Review",
  "Son təsdiq": "Final confirmation",
  "Tarix və seçimlər": "Dates and options",
  "Sizin məlumatlar": "Your details",
  "Son bir neçə": "A few final",
  "detal.": "details.",
  "Son bir neçə detal.": "A few final details.",
  "Seçilmiş": "Selected",
  "SEÇİLMİŞ": "SELECTED",
  "seçilmiş": "selected",
  "Avtomobil artıq seçilib. Səfər məlumatlarını yoxlayın, əlaqə məlumatlarınızı daxil edin və sorğunu Carbon komandasına göndərin.": "The car is already selected. Check trip details, enter your contact information and send the request to the Carbon team.",
  "Səfərinizi yoxlayın.": "Review your trip.",
  "Avtomobili məntəqədən təhvil alın": "Pick up the car from our office",
  "Avtomobil seçdiyiniz ünvana gəlsin": "Have the car delivered to your address",
  "ÇATDIRILMA ÜNVANI": "DELIVERY ADDRESS",
  "Məsələn: Nizami küç. 90": "Example: Nizami St. 90",
  "NÖVBƏTİ ADDIM": "NEXT STEP",
  "Əlaqə məlumatları": "Contact details",
  "Sizinlə necə əlaqə saxlayaq?": "How should we contact you?",
  "AD VƏ SOYAD": "FULL NAME",
  "Məlumatlar yalnız rezervasiya üçün istifadə olunur.": "The information is used only for the reservation.",
  "Sorğu göndərilməsi avtomatik ödəniş və ya yekun rezervasiya yaratmır.": "Sending a request does not create automatic payment or a final reservation.",
  "Hər şey hazırdır.": "Everything is ready.",
  "AVTOMOBİL": "CAR",
  "SƏFƏR": "TRIP",
  "ƏLAQƏ": "CONTACT",
  "GÜNLÜK TARİF": "DAILY RATE",
  "TƏXMİNİ MƏBLƏĞ": "ESTIMATED TOTAL",
  "SORĞUNU TAMAMLA": "COMPLETE REQUEST",
  "WhatsApp ilə göndər": "Send via WhatsApp",
  "Məlumatları dəyiş": "Edit details",
  "Sorğunuz": "Your request",
  "hazırdır.": "is ready.",
  "WhatsApp açılır və rezervasiya məlumatları avtomatik hazırlanır. Mesajı göndərdikdən sonra Carbon komandası mövcudluğu təsdiqləyəcək.": "WhatsApp opens and reservation details are prepared automatically. After you send the message, the Carbon team will confirm availability.",
  "WhatsApp-ı yenidən aç": "Open WhatsApp again",
  "CANLI XÜLASƏ": "LIVE SUMMARY",
  "Müddət": "Duration",
  "Günlük tarif": "Daily rate",
  "Təxmini məbləğ": "Estimated total",
  "Ödəniş yalnız mövcudluq və şərtlər təsdiqləndikdən sonra.": "Payment is made only after availability and terms are confirmed.",
  "Aydın proses": "Clear process",
  "Göndərmə ödəniş demək deyil": "Sending is not payment",
  "Birbaşa komanda": "Direct team",
  "Sorğu real əməkdaş tərəfindən yoxlanılır": "The request is reviewed by a real team member",
  "Qiymət seçilmiş müddətə görə hesablanır": "Price is calculated by selected duration"
  ,
  "Yolu daha rahat": "We make the road",
  "edirik.": "more comfortable.",
  "Müasir avtomobil icarəsi xidməti — həvəskarlar və peşəkarlar üçün.": "Modern car rental service for enthusiasts and professionals.",
  "Carbon Rent A Car sürətli, etibarlı və rahat avtomobil kirayəsi xidmətidir. Müştərilərimizə hər zaman saz, təmiz və sığortalı avtomobillər təqdim edirik.": "Carbon Rent A Car is a fast, reliable and comfortable car rental service. We always provide clean, well-maintained and insured vehicles.",
  "Komfortlu səyahət,": "Comfortable travel,",
  "etibarlı xidmət.": "reliable service.",
  "Məqsədimiz sizə problemsiz, təhlükəsiz və yüksək keyfiyyətli xidmət göstərməkdir.": "Our goal is to provide seamless, safe and high-quality service.",
  "Tam sığortalı avtomobillər": "Fully insured vehicles",
  "CARBON RƏQƏMLƏRLƏ": "CARBON IN NUMBERS",
  "BİZİM MİSSİYAMIZ": "OUR MISSION",
  "Rahatlıq.": "Comfort.",
  "Təhlükəsizlik.": "Safety.",
  "Etibar.": "Trust.",
  "Müştərilərimizə təhlükəsiz, rahat və şəffaf avtomobil kirayəsi xidməti təqdim edərək onların səyahətlərini daha rahat, problemsiz və etibarlı etməyi hədəfləyirik.": "We aim to make our customers' journeys more comfortable, seamless and reliable by providing safe, transparent car rental service.",
  "“Sizin yolunuzu rahatlıq və etibar ilə təmin edirik.”": "\"We support your road with comfort and trust.\"",
  "CARBON HƏKAYƏSİ": "CARBON STORY",
  "BİZİ DAHA YAXINDAN TANIYIN": "GET TO KNOW US BETTER",
  "komandasından.": "team.",
  "Xidmət yanaşmamızı, müştəri təcrübəsinə baxışımızı və Carbon-un arxasındakı insanları üç qısa videoda izləyin.": "Watch our service approach, our view of customer experience and the people behind Carbon in three short videos.",
  "DƏYƏRLƏRİMİZ": "OUR VALUES",
  "Bizim üçün": "For us",
  "standart budur.": "this is the standard.",
  "Carbon Rent A Car olaraq məqsədimiz hər bir müştəriyə etibarlı, rahat və problemsiz icarə təcrübəsi təqdim etməkdir.": "At Carbon Rent A Car, our goal is to provide every customer with a reliable, comfortable and seamless rental experience.",
  "Etibar": "Trust",
  "Hər icarə prosesində açıq kommunikasiya, təhlükəsiz xidmət və məsuliyyətli yanaşma.": "Clear communication, safe service and a responsible approach in every rental process.",
  "Hər detalı sizin rahatlığınız və problemsiz təcrübəniz üçün düşünürük.": "We think through every detail for your comfort and seamless experience.",
  "NİYƏ MƏHZ BİZ?": "WHY CHOOSE US?",
  "Siz seçin.": "You choose.",
  "Qalanını biz həll edək.": "We'll take care of the rest.",
  "Tam kasko sığorta": "Full casco insurance",
  "Depozit qaytarılmasına zəmanət": "Deposit return guarantee",
  "24/7 texniki dəstək": "24/7 technical support",
  "Dəstək": "Support",
  "Şəffaf proses": "Transparent process",
  "AKTİV": "ACTIVE",
  "Müştəriyönümlü yanaşma": "Customer-focused approach",
  "Hər icarə mərhələsində rahatlığınızı və məmnuniyyətinizi əsas götürürük.": "We prioritize your comfort and satisfaction at every rental stage.",
  "HƏR MƏRHƏLƏDƏ YANINIZDA": "WITH YOU AT EVERY STAGE",
  "Müasir həllər": "Modern solutions",
  "Asan rezervasiya, şəffaf qiymətlər və 24/7 dəstək ilə yolunuzda yanınızdayıq.": "With easy reservation, transparent prices and 24/7 support, we are with you on the road.",
  "SÜRƏTLİ · SADƏ · ŞƏFFAF": "FAST · SIMPLE · TRANSPARENT",
  "Rahatlıq standart deyil.": "Comfort is not a standard.",
  "Bizim standartımızdır.": "It is our standard.",
  "OFİSİMİZ": "OUR OFFICE",
  "BAKI · AZƏRBAYCAN": "BAKU · AZERBAIJAN",
  "Gəlin": "Come",
  "tanış olaq.": "meet us.",
  "TELEFON": "PHONE",
  "Carbon mərkəzi": "Carbon center",
  "MARŞRUTU AÇ": "OPEN ROUTE",
  "Google Maps-də aç": "Open in Google Maps",
  "OFİS AKTİVDİR": "OFFICE ACTIVE",
  "ƏLƏSGƏR QAYIBOV 12/22": "ALASGAR GAYIBOV 12/22",
  "Avtomobil hazırdır.": "The car is ready.",
  "Siz tarixi seçin.": "Choose your dates.",
  "Tarixləri seçin və təxmini qiyməti dərhal görün. Son təsdiqdən əvvəl komandamız mövcudluğu və bütün şərtləri sizinlə dəqiqləşdirəcək.": "Select dates and see the estimated price instantly. Before final confirmation, our team will confirm availability and all terms with you.",
  "Aydın şərtlər": "Clear terms",
  "Gizli addım yoxdur": "No hidden steps",
  "Birbaşa dəstək": "Direct support",
  "Carbon komandası ilə": "With the Carbon team",
  "Ödənişsiz sorğu": "Free request",
  "Əvvəl təsdiq, sonra proses": "Confirmation first, process after",
  "Rezervasiyanı təsdiqlə": "Confirm reservation",
  "Sorğu göndərmə ödəniş yaratmır. Mövcudluq və yekun şərtlər Carbon komandası tərəfindən təsdiqlənir.": "Sending a request does not create a payment. Availability and final terms are confirmed by the Carbon team.",
  "Avtomobil hazırdır": "The car is ready",
  "Siz tarixi seçin": "Choose your dates",
  "Səfərinizi qurun.": "Set up your trip.",
  "Sorğu açıqdır": "Request is open",
  "Seçilmiş müddət üçün": "For the selected duration",
  "İstəyə bağlı": "Optional",
  "seçilib": "selected"
};

const ru: Record<string, string> = {
  "Azərbaycan": "Азербайджан",
  "Bakı": "Баку",
  "Bakı, Azərbaycan": "Баку, Азербайджан",
  "Ələsgər Qayıbov küç. 1222": "ул. Алескера Гаибова 12/22",
  "Ələsgər Qayıbov 12/22, Bakı": "Алескер Гаибов 12/22, Баку",
  "Ana səhifə": "Главная",
  "Avtomobillər": "Автомобили",
  "Toy avtomobilləri": "Свадебные автомобили",
  "Haqqımızda": "О нас",
  "Xidmətlər": "Услуги",
  "Əlaqə": "Контакты",
  "Əlaqə saxla": "Связаться",
  "Bizimlə əlaqə": "Связаться с нами",
  "Avtomobil seç": "Выбрать автомобиль",
  "Avtomobil seçin": "Выберите автомобиль",
  "Bütün avtomobillər": "Все автомобили",
  "Avtomobillərə bax": "Смотреть автомобили",
  "Kolleksiyaya bax": "Смотреть коллекцию",
  "Kolleksiyanı araşdır": "Изучить коллекцию",
  "Transfer avtomobilləri": "Авто для трансфера",
  "Transfer xidməti": "Трансфер",
  "Toy kolleksiyası": "Свадебная коллекция",
  "Müraciət et": "Оставить заявку",
  "Sorğu ilə": "По запросу",
  "Sorğu": "Запрос",
  "Qiymət üçün əlaqə": "Уточнить цену",
  "/ gün": "/ день",
  "gün": "день",
  "GÜN": "ДН.",
  "nəfər": "чел.",
  "yer": "мест",
  "Hamısı": "Все",
  "Filtrlər": "Фильтры",
  "Sıfırla": "Сбросить",
  "Təmizlə": "Очистить",
  "Bağla": "Закрыть",
  "Hazırdır": "Готово",
  "Bu gün": "Сегодня",
  "Tarix seçin": "Выберите дату",
  "Seçilməyib": "Не выбрано",
  "Əvvəlki ay": "Предыдущий месяц",
  "Növbəti ay": "Следующий месяц",
  "Götürülmə": "Получение",
  "Qaytarılma": "Возврат",
  "GÖTÜRMƏ": "ПОЛУЧЕНИЕ",
  "QAYTARMA": "ВОЗВРАТ",
  "GÖTÜRMƏ TARİXİ": "ДАТА ПОЛУЧЕНИЯ",
  "QAYTARMA TARİXİ": "ДАТА ВОЗВРАТА",
  "TƏHVİL": "ПЕРЕДАЧА",
  "Təhvil": "Передача",
  "Təhvil üsulu": "Способ передачи",
  "Carbon məntəqəsi": "Офис Carbon",
  "Ünvana çatdırılma": "Доставка по адресу",
  "Çatdırılma": "Доставка",
  "Məntəqədən təhvil": "Получение в офисе",
  "Sürücü": "Водитель",
  "SÜRÜCÜ": "ВОДИТЕЛЬ",
  "Sürücü ilə": "С водителем",
  "Sürücüsüz": "Без водителя",
  "Əlavə sürücü": "Дополнительный водитель",
  "SÜRÜCÜ SAYI": "КОЛИЧЕСТВО ВОДИТЕЛЕЙ",
  "ƏLAVƏ XİDMƏTLƏR": "ДОПОЛНИТЕЛЬНЫЕ УСЛУГИ",
  "ƏLAVƏ QEYD": "ДОПОЛНИТЕЛЬНАЯ ЗАМЕТКА",
  "Prioritet dəstək": "Приоритетная поддержка",
  "Rezervasiya": "Бронирование",
  "REZERVASİYA": "БРОНИРОВАНИЕ",
  "Rezervasiya et": "Забронировать",
  "Sürətli rezervasiya": "Быстрое бронирование",
  "SORĞU SİSTEMİ AKTİVDİR": "СИСТЕМА ЗАЯВОК АКТИВНА",
  "Sistem aktivdir": "Система активна",
  "DAVAM ET": "ПРОДОЛЖИТЬ",
  "Seçim edin": "Сделайте выбор",
  "Nəticələri göstər": "Показать результаты",
  "NƏTİCƏ": "РЕЗУЛЬТАТ",
  "uyğun nəticə": "подходящих результатов",
  "avtomobil göstərilir": "автомобилей показано",
  "Uyğun avtomobil tapılmadı.": "Подходящий автомобиль не найден.",
  "Avtomobil tapılmadı": "Автомобиль не найден",
  "Avtomobil tapılmadı.": "Автомобиль не найден.",
  "Axtarışı dəyişin və ya aktiv filtrləri sıfırlayın.": "Измените поиск или сбросьте активные фильтры.",
  "Axtarışı və ya kateqoriyanı dəyişin.": "Измените поиск или категорию.",
  "Bütün avtomobilləri göstər": "Показать все автомобили",
  "Səyahətinizə uyğun avtomobili tapın": "Найдите автомобиль под вашу поездку",
  "Avtomobili detallara görə seçin": "Выберите автомобиль по деталям",
  "ƏTRAFLI FİLTRLƏR": "ПОДРОБНЫЕ ФИЛЬТРЫ",
  "İstehsalçı": "Производитель",
  "Sərnişin sayı": "Количество пассажиров",
  "Çamadan tutumu": "Вместимость багажа",
  "Kiçik baqaj tutumu": "Малый багаж",
  "Sürətlər qutusu": "Коробка передач",
  "Yanacaq növü": "Тип топлива",
  "Mühərrik həcmi": "Объем двигателя",
  "Ətraflı baxış": "Подробнее",
  "seç və rezerv et": "выбрать и забронировать",
  "Carbon seçimi": "Выбор Carbon",
  "Əvvəl ucuz": "Сначала дешевле",
  "Əvvəl premium": "Сначала премиум",
  "Ada görə": "По названию",
  "Əlaqə və": "Контакты и",
  "dəstək.": "поддержка.",
  "DƏSTƏK XƏTTİ AKTİVDİR": "ЛИНИЯ ПОДДЕРЖКИ АКТИВНА",
  "ƏLAQƏ KANALLARI": "КАНАЛЫ СВЯЗИ",
  "Birbaşa Carbon komandası": "Напрямую с командой Carbon",
  "Yazılı müraciətlər üçün": "Для письменных обращений",
  "ÜNVAN": "АДРЕС",
  "MÜRACİƏT MƏRKƏZİ": "ЦЕНТР ОБРАЩЕНИЙ",
  "BİZƏ YAZIN": "НАПИШИТЕ НАМ",
  "Nə barədə": "О чем вы хотите",
  "danışmaq istəyirsiniz?": "поговорить?",
  "Uyğun müraciət növünü seçin. Forma yalnız sizə lazım olan məlumatları göstərəcək.": "Выберите тип обращения. Форма покажет только нужные поля.",
  "Ümumi sorğu": "Общий запрос",
  "Sualınız var?": "Есть вопрос?",
  "İcarə, avtomobillər, rezervasiya və xidmətlər haqqında bizə yazın.": "Напишите нам об аренде, автомобилях, бронировании и услугах.",
  "Şikayət": "Жалоба",
  "Problem bildirin": "Сообщить о проблеме",
  "Qarşılaşdığınız problemi ətraflı paylaşın. Hər müraciət diqqətlə araşdırılır.": "Подробно опишите проблему. Каждое обращение внимательно рассматривается.",
  "Rəy": "Отзыв",
  "Təcrübənizi bölüşün": "Поделитесь опытом",
  "Xidmət təcrübənizi bizimlə paylaşın və daha yaxşı olmağımıza kömək edin.": "Поделитесь опытом обслуживания и помогите нам стать лучше.",
  "SEÇİLİB": "ВЫБРАНО",
  "SEÇ": "ВЫБРАТЬ",
  "Məlumatlarınız yalnız müraciətinizi cavablandırmaq məqsədilə istifadə olunur.": "Ваши данные используются только для ответа на обращение.",
  "ÜMUMİ MÜRACİƏT": "ОБЩЕЕ ОБРАЩЕНИЕ",
  "ŞİKAYƏT FORMASI": "ФОРМА ЖАЛОБЫ",
  "RƏY FORMASI": "ФОРМА ОТЗЫВА",
  "Sualınızı bizə göndərin.": "Отправьте нам вопрос.",
  "Problemi bizə bildirin.": "Сообщите нам о проблеме.",
  "Təcrübənizi paylaşın.": "Поделитесь опытом.",
  "2 dəq.": "2 мин.",
  "AD": "ИМЯ",
  "SOYAD": "ФАМИЛИЯ",
  "Adınız": "Ваше имя",
  "Soyadınız": "Ваша фамилия",
  "Adınız və soyadınız": "Ваше имя и фамилия",
  "ƏLAQƏ NÖMRƏSİ": "КОНТАКТНЫЙ НОМЕР",
  "MÖVZU": "ТЕМА",
  "Mövzu": "Тема",
  "Müraciətin mövzusunu seçin": "Выберите тему обращения",
  "Avtomobil seçimi": "Выбор автомобиля",
  "Qiymət və depozit": "Цена и депозит",
  "Sığorta": "Страховка",
  "Digər": "Другое",
  "ŞİKAYƏTİNİZ NƏ İLƏ BAĞLIDIR?": "С ЧЕМ СВЯЗАНА ЖАЛОБА?",
  "Kateqoriya seçin": "Выберите категорию",
  "Ödəniş / depozit": "Оплата / депозит",
  "Əməkdaş / xidmət": "Сотрудник / сервис",
  "Təhvil / qaytarılma": "Передача / возврат",
  "İCARƏ TARİXİ": "ДАТА АРЕНДЫ",
  "AVTOMOBİLİN MARKASI / MODELİ": "МАРКА / МОДЕЛЬ АВТО",
  "XİDMƏT GÖSTƏRƏN ƏMƏKDAŞ": "СОТРУДНИК",
  "Adı bilirsinizsə qeyd edin": "Укажите имя, если знаете",
  "RƏYİNİZ": "ВАШ ОТЗЫВ",
  "ŞİKAYƏTİNİZ": "ВАША ЖАЛОБА",
  "MESAJINIZ": "ВАШЕ СООБЩЕНИЕ",
  "Təcrübənizi bizimlə bölüşün...": "Поделитесь опытом...",
  "Qarşılaşdığınız vəziyyəti mümkün qədər ətraflı izah edin...": "Опишите ситуацию как можно подробнее...",
  "Sualınızı və ya müraciətinizi yazın...": "Напишите вопрос или обращение...",
  "Göndər düyməsi cihazınızda email tətbiqini müraciət məlumatları ilə açacaq.": "Кнопка отправки откроет почтовое приложение с деталями обращения.",
  "Müraciəti hazırla": "Подготовить обращение",
  "MÜRACİƏT HAZIRDIR": "ОБРАЩЕНИЕ ГОТОВО",
  "Emailiniz": "Ваш email",
  "hazırlanır.": "готовится.",
  "Email tətbiqiniz açıldıqda məlumatları yoxlayıb göndərə bilərsiniz.": "Когда откроется почтовое приложение, проверьте данные и отправьте.",
  "MÜRACİƏT KODU": "КОД ОБРАЩЕНИЯ",
  "Formaya qayıt": "Вернуться к форме",
  "Səfərdən əvvəl,": "До поездки,",
  "səfər zamanı,": "во время поездки,",
  "səfərdən sonra.": "после поездки.",
  "Məqsədimiz sadəcə avtomobil təqdim etmək deyil. Bütün icarə təcrübəsi boyunca sizin üçün əlçatan qalmaqdır.": "Наша цель - не просто предоставить автомобиль. Мы остаемся на связи на протяжении всей аренды.",
  "İndi zəng et": "Позвонить сейчас",
  "MƏQALƏ": "СТАТЬЯ",
  "Növbəti oxu.": "Следующее чтение.",
  "Bütün məqalələr": "Все статьи",
  "Yol üçün": "Лучшие идеи",
  "daha yaxşı fikirlər.": "для дороги.",
  "Avtomobil, səyahət, sığorta və düzgün seçim haqqında qısa, praktik bələdçilər.": "Короткие практичные гиды об авто, поездках, страховке и правильном выборе.",
  "Kateqoriya": "Категория",
  "Seçilmiş məqalə": "Избранная статья",
  "Son yazılar": "Последние статьи",
  "Oxumağa başla": "Начать читать",
  "Oxu": "Читать",
  "Oxumaq kifayətdir.": "Достаточно прочитать.",
  "İndi yola çıx.": "Теперь в путь.",
  "Qiymət və Sığorta Maarifləndirməsi": "Цена и страховка",
  "Ucuz avtomobil kirayəsi hər zaman sərfəlidirmi?": "Всегда ли выгодна дешевая аренда авто?",
  "Kirayə Məsləhətləri": "Советы по аренде",
  "Səyahət Marşrutları və Tövsiyələri": "Маршруты и рекомендации",
  "Avtomobil Baxımı və Texniki Məlumatlar": "Уход за авто и техническая информация",
  "Niyə Carbon Rent A Car-ı Seçirlər?": "Почему выбирают Carbon Rent A Car",
  "İcarə bələdçisi": "Гид по аренде",
  "Məsləhətlər": "Советы",
  "Səyahət": "Путешествия",
  "5 dəq": "5 мин",
  "4 dəq": "4 мин",
  "6 dəq": "6 мин",
  "7 dəq": "7 мин",
  "Haqqımızda | Carbon Rent A Car": "О нас | Carbon Rent A Car",
  "Məmnun müştəri": "Довольных клиентов",
  "İllik təcrübə": "Лет опыта",
  "Premium avtomobil icarəyə verilib": "Премиальных авто в аренде",
  "Müştəri məmnuniyyəti": "Удовлетворенность клиентов",
  "Keyfiyyət": "Качество",
  "Saz, təmiz və premium standartlara uyğun avtomobillər.": "Чистые и исправные автомобили премиум-стандарта.",
  "Şəffaf şərtlər": "Прозрачные условия",
  "Geniş avtomobil seçimi": "Широкий выбор авто",
  "Etibar və xidmət": "Доверие и сервис",
  "Səsi aç": "Включить звук",
  "Səsi bağla": "Выключить звук",
  "Dayandır": "Пауза",
  "Hava Limanı": "Аэропорт",
  "Hava limanı": "Аэропорт",
  "Gündəlik": "Ежедневная",
  "Uzunmüddətli": "Долгосрочная",
  "SUV və": "SUV и",
  "off-road icarəsi.": "off-road аренда.",
  "Sərbəst": "Свободно",
  "Həftəlik": "Еженедельно",
  "Aylıq": "Ежемесячно",
  "Servis daxil": "Сервис включен",
  "Tam sığorta": "Полная страховка",
  "Tam sığortalı": "Полностью застраховано",
  "Geniş seçim": "Широкий выбор",
  "Premium xidmət": "Премиальный сервис",
  "Bakı və regionlar": "Баку и регионы",
  "Xidmətlərimiz | Carbon Rent A Car": "Наши услуги | Carbon Rent A Car",
  "Şərtlər və Qaydalar | Carbon Rent A Car": "Условия и правила | Carbon Rent A Car",
  "Məxfilik Siyasəti | Carbon Rent A Car": "Политика конфиденциальности | Carbon Rent A Car",
  "Hüquqi məlumat": "Юридическая информация",
  "Şərtlər və Qaydalar": "Условия и правила",
  "Ən son yeniləmə: 24 iyul 2025": "Последнее обновление: 24 июля 2025",
  "9 bölmə": "9 разделов",
  "Giriş": "Введение",
  "Rezervasiya Şərtləri": "Условия бронирования",
  "Ödəniş və Depozit Qaydaları": "Оплата и депозит",
  "Təslim və Qaytarılma Qaydaları": "Правила передачи и возврата",
  "Sığorta Şərtləri": "Условия страховки",
  "İstifadə Məhdudiyyətləri": "Ограничения использования",
  "Texniki Problem Halları": "Технические проблемы",
  "Müştərinin Məsuliyyəti": "Ответственность клиента",
  "Şirkətin Hüquqları": "Права компании",
  "Şərtlərlə bağlı sualınız var?": "Есть вопрос по условиям?",
  "Carbon Rent A Car xidmətlərindən istifadə, rezervasiya, ödəniş, avtomobilin təhvil alınması və qaytarılması üçün tətbiq olunan əsas şərtlər.": "Основные условия использования услуг Carbon Rent A Car, бронирования, оплаты, получения и возврата автомобиля.",
  "Carbon Rent A Car xidmətlərindən istifadə etməklə, aşağıda qeyd olunan şərtləri qəbul etmiş olursunuz.": "Пользуясь услугами Carbon Rent A Car, вы принимаете указанные ниже условия.",
  "Bu şərtlər saytımız vasitəsilə edilən bütün rezervasiyalara və kirayə müqavilələrinə şamil olunur.": "Эти условия применяются ко всем бронированиям и договорам аренды, оформленным через наш сайт.",
  "Avtomobil kirayə etmək üçün minimum yaş həddi 21 yaşdır.": "Минимальный возраст для аренды автомобиля - 21 год.",
  "Müştərinin etibarlı sürücülük vəsiqəsi olmalıdır və minimum 1 il sürücülük təcrübəsi tələb olunur.": "У клиента должно быть действующее водительское удостоверение и минимум 1 год водительского стажа.",
  "Rezervasiya zamanı düzgün şəxsi məlumatların təqdim edilməsi mütləqdir.": "При бронировании необходимо предоставить корректные личные данные.",
  "Ödəniş nağd, kartla və ya online mümkündür.": "Оплата возможна наличными, картой или онлайн.",
  "Depozit məbləği avtomobilin sinfi, icarə müddəti, sürücülük təcrübəsi və digər amillər nəzərə alınmaqla təyin edilə və ya edilməyə bilər.": "Сумма депозита может назначаться с учетом класса автомобиля, срока аренды, водительского стажа и других факторов.",
  "Depozit təyin olunubsa, götürülmüş depozit müqavilədə mütləq şəkildə öz əksini tapmalıdır.": "Если депозит назначен, он обязательно должен быть отражен в договоре.",
  "Kirayə müddəti bitdikdən sonra avtomobil qaytarılarkən hər hansı cərimə və ya zərər olmadığı halda depozit tam şəkildə qaytarılır.": "После окончания аренды депозит полностью возвращается при отсутствии штрафов или повреждений.",
  "Avtomobil razılaşdırılmış tarix və saatda təhvil verilir.": "Автомобиль передается в согласованные дату и время.",
  "Qaytarılma gecikərsə, əlavə ödəniş tətbiq oluna bilər.": "При задержке возврата может применяться дополнительная оплата.",
  "Avtomobil eyni yanacaq səviyyəsi ilə qaytarılmalıdır.": "Автомобиль должен быть возвращен с тем же уровнем топлива.",
  "Bütün avtomobillər icbari və kasko sığorta ilə təmin olunub.": "Все автомобили обеспечены обязательной и КАСКО-страховкой.",
  "Qəza halında dərhal şirkət və DYP ilə əlaqə saxlanılmalıdır.": "В случае аварии необходимо немедленно связаться с компанией и дорожной полицией.",
  "Avtomobilin üçüncü şəxslərə verilməsi qadağandır.": "Передача автомобиля третьим лицам запрещена.",
  "Avtomobil yalnız Azərbaycan Respublikasının ərazisində istifadə oluna bilər.": "Автомобиль можно использовать только на территории Азербайджанской Республики.",
  "Avtomobildən qanunsuz fəaliyyətlərdə və sürücülük qaydalarını pozan hallarda istifadə qəti qadağandır.": "Использование автомобиля в незаконных действиях или с нарушением правил вождения строго запрещено.",
  "Avtomobilin nasazlığı zamanı dərhal bizimlə əlaqə saxlayın.": "При неисправности автомобиля немедленно свяжитесь с нами.",
  "Zərurət yarandıqda 24/7 texniki yardım və əvəz avtomobil təqdim olunur.": "При необходимости предоставляется техническая помощь 24/7 и заменяющий автомобиль.",
  "Müştəri avtomobilə vurduğu hər hansı zərəri kompensasiya etməklə məsuldur.": "Клиент несет ответственность за компенсацию любого ущерба автомобилю.",
  "Avtomobilin salonunun təmiz saxlanılması və avtomobildən istismar qaydalarına uyğun istifadə edilməsi tələb olunur.": "Салон автомобиля должен содержаться в чистоте, а автомобиль использоваться по правилам эксплуатации.",
  "Şirkət zəruri hallarda — sənədlərin uyğun olmaması və ya təhlükəsizlik səbəbləri daxil olmaqla — sifarişi qəbul etməmək hüququna malikdir.": "Компания вправе отказать в заказе при необходимости, включая несоответствие документов или причины безопасности.",
  "Şirkət bu şərtləri xəbərdarlıq etmədən dəyişdirmək hüququnu özündə saxlayır.": "Компания оставляет за собой право изменять эти условия без предупреждения.",
  "Dəyişikliklər saytımızda elan olunduğu tarixdən qüvvəyə minir.": "Изменения вступают в силу с даты публикации на сайте.",
  "Rezervasiya və ya kirayə şərtləri ilə bağlı əlavə məlumat üçün komandamızla əlaqə saxlaya bilərsiniz.": "Для дополнительной информации о бронировании или условиях аренды свяжитесь с нашей командой.",
  "Carbon Rent A Car komandası olaraq xidmətimizdən istifadə etdiyiniz üçün təşəkkür edirik və sizə rahat, təhlükəsiz səyahətlər arzulayırıq.": "Команда Carbon Rent A Car благодарит вас за использование сервиса и желает комфортных и безопасных поездок.",
  "Məxfilik Siyasəti": "Политика конфиденциальности",
  "10 bölmə": "10 разделов",
  "Məxfilik üzrə əlaqə": "Контакт по конфиденциальности",
  "Toplanan Məlumatlar": "Собираемые данные",
  "Məlumatların Toplanma Yolları": "Способы сбора данных",
  "Məlumatların İstifadə Edilməsi": "Использование данных",
  "Məlumatların Paylaşılması": "Передача данных",
  "Təhlükəsizlik": "Безопасность",
  "Məlumatların Saxlanması Müddəti": "Срок хранения данных",
  "İstifadəçi Hüquqları": "Права пользователя",
  "Cookies Siyasəti": "Политика cookies",
  "Dəyişikliklər": "Изменения",
  "Məlumatlarınızla bağlı sualınız var?": "Есть вопрос по вашим данным?",
  "Məxfilik Siyasətimiz şəxsi məlumatlarınızın necə toplanması, istifadəsi və qorunması barədə məlumat verir. Məxfiliyiniz və təhlükəsizliyiniz bizim üçün prioritetdir.": "Наша политика конфиденциальности объясняет, как собираются, используются и защищаются ваши персональные данные. Ваша конфиденциальность и безопасность для нас приоритет.",
  "Carbon Rent A Car olaraq müştərilərimizin məxfiliyinə hörmətlə yanaşırıq və şəxsi məlumatlarınızın qorunmasına sadiqik.": "В Carbon Rent A Car мы уважаем конфиденциальность клиентов и заботимся о защите ваших персональных данных.",
  "Bu məxfilik siyasəti sizə hansı məlumatları topladığımızı, necə istifadə etdiyimizi və qoruduğumuzu izah edir.": "Эта политика объясняет, какие данные мы собираем, как используем и защищаем их.",
  "Saytımız vasitəsilə aşağıdakı şəxsi məlumatları toplaya bilərik:": "Через сайт мы можем собирать следующие персональные данные:",
  "Ad və soyad": "Имя и фамилия",
  "Telefon nömrəsi": "Номер телефона",
  "Email ünvanı": "Email адрес",
  "Rezervasiya tarixləri və avtomobil seçimi": "Даты бронирования и выбор автомобиля",
  "Ödəniş məlumatları — online ödəniş etdiyiniz halda": "Платежные данные, если вы оплачиваете онлайн",
  "İstifadəçi davranış məlumatları — cookies və analitika vasitəsilə": "Данные поведения пользователя через cookies и аналитику",
  "Topladığımız məlumatlar aşağıdakı məqsədlərlə istifadə edilir:": "Собранные данные используются для следующих целей:",
  "Rezervasiyanızı təsdiqləmək və xidmət göstərmək": "Подтверждение бронирования и оказание услуги",
  "Müştəri xidmətləri üçün əlaqə yaratmaq": "Связь для клиентского сервиса",
  "Təhlükəsizlik və fırıldaqçılığın qarşısını almaq": "Обеспечение безопасности и предотвращение мошенничества",
  "Kampaniya və yeniliklər barədə məlumat göndərmək — yalnız razılığınız varsa": "Отправка информации об акциях и новостях только при вашем согласии",
  "Saytın və xidmətlərimizin inkişafı üçün təhlil aparmaq": "Анализ для улучшения сайта и услуг",
  "Şəxsi məlumatlarınız üçüncü tərəflərlə paylaşılmır. Aşağıdakı hallar istisna təşkil edir:": "Ваши персональные данные не передаются третьим лицам, кроме следующих случаев:",
  "Məlumatlarınızın qorunması üçün zəruri texniki və təşkilati təhlükəsizlik tədbirləri görülür.": "Для защиты данных принимаются необходимые технические и организационные меры.",
  "Rezervasiya və əlaqə məlumatları xidmət müddəti və qanunvericiliyə uyğun olaraq saxlanılır.": "Данные бронирования и контактов хранятся согласно сроку услуги и законодательству.",
  "Siz aşağıdakı hüquqlara maliksiniz:": "Вы имеете следующие права:",
  "Şəxsi məlumatlarınıza çıxış etmək": "Получить доступ к персональным данным",
  "Onları düzəltmək və ya yeniləmək": "Исправить или обновить их",
  "Bu hüquqlarla bağlı müraciət etmək üçün bizimlə əlaqə saxlaya bilərsiniz.": "Чтобы воспользоваться этими правами, свяжитесь с нами.",
  "Saytımız istifadəçi təcrübəsini yaxşılaşdırmaq üçün cookies istifadə edir. Cookies-i brauzerinizin ayarlarından idarə edə və ya silə bilərsiniz.": "Наш сайт использует cookies для улучшения пользовательского опыта. Вы можете управлять ими или удалить их в настройках браузера.",
  "Saytımızdan istifadə etməklə cookies siyasətimizə razılıq vermiş olursunuz.": "Используя сайт, вы соглашаетесь с нашей политикой cookies.",
  "Məxfilik siyasətimiz zaman-zaman yenilənə bilər. Dəyişikliklər bu səhifədə yerləşdirilir və yenilənmə tarixi göstərilir.": "Политика конфиденциальности может обновляться. Изменения публикуются на этой странице с датой обновления.",
  "Siyasəti mütəmadi olaraq nəzərdən keçirməyiniz tövsiyə olunur.": "Рекомендуем регулярно просматривать политику.",
  "Şəxsi məlumatlarınıza çıxış, düzəliş və ya məxfilik siyasəti ilə bağlı bizimlə əlaqə saxlaya bilərsiniz.": "По вопросам доступа, исправления данных или политики конфиденциальности свяжитесь с нами.",
  "Carbon Rent A Car komandası olaraq şəxsi məlumatlarınızın qorunmasına daim diqqət yetiririk. Bizi seçdiyiniz üçün təşəkkür edirik.": "Команда Carbon Rent A Car всегда уделяет внимание защите ваших персональных данных. Спасибо, что выбрали нас.",
  "Toy Avtomobilləri | Carbon Rent A Car": "Свадебные автомобили | Carbon Rent A Car",
  "XÜSUSİ GÜNLƏR ÜÇÜN": "ДЛЯ ОСОБЫХ ДНЕЙ",
  "Qiymət": "Цена",
  "/ başlayır": "/ от",
  "başlayır": "от",
  "Tarix üzrə rezervasiya": "Бронирование по дате",
  "Tədbir gününüzə uyğun planlama": "Планирование под день события",
  "Vaxtın dəqiqləşdirilməsi": "Уточнение времени",
  "Komandamız sizinlə əvvəlcədən əlaqə saxlayır": "Команда заранее связывается с вами",
  "Etibarlı xidmət": "Надежный сервис",
  "Tarix və detalları dəqiqləşdirin": "Уточните дату и детали",
  "XİDMƏT PROSESİ": "ПРОЦЕСС УСЛУГИ",
  "Sadə və": "Просто и",
  "aydın.": "понятно.",
  "Avtomobili seçin": "Выберите автомобиль",
  "Tarixi bildirin": "Сообщите дату",
  "Detalları razılaşdırın": "Согласуйте детали",
  "Günün dadını çıxarın": "Наслаждайтесь днем",
  "Bilmək istədiyiniz": "Все, что вы хотите",
  "hər şey.": "узнать.",
  "DİGƏR SEÇİMLƏR": "ДРУГИЕ ВАРИАНТЫ",
  "Digər toy avtomobilləri": "Другие свадебные автомобили",
  "Hamısına bax": "Смотреть все",
  "Xüsusi gününüz": "Ваш особый день",
  "Carbon ilə.": "с Carbon.",
  "Avtomobillərə qayıt": "Вернуться к автомобилям",
  "Avtomobilə qayıt": "Вернуться к авто",
  "Səfər": "Поездка",
  "Yoxlama": "Проверка",
  "Son təsdiq": "Финальное подтверждение",
  "Tarix və seçimlər": "Даты и опции",
  "Sizin məlumatlar": "Ваши данные",
  "Son bir neçə": "Несколько последних",
  "detal.": "деталей.",
  "Son bir neçə detal.": "Несколько последних деталей.",
  "Seçilmiş": "Выбрано",
  "SEÇİLMİŞ": "ВЫБРАНО",
  "seçilmiş": "выбрано",
  "Səfərinizi yoxlayın.": "Проверьте поездку.",
  "ÇATDIRILMA ÜNVANI": "АДРЕС ДОСТАВКИ",
  "NÖVBƏTİ ADDIM": "СЛЕДУЮЩИЙ ШАГ",
  "Əlaqə məlumatları": "Контактные данные",
  "Sizinlə necə əlaqə saxlayaq?": "Как с вами связаться?",
  "AD VƏ SOYAD": "ИМЯ И ФАМИЛИЯ",
  "Hər şey hazırdır.": "Все готово.",
  "AVTOMOBİL": "АВТОМОБИЛЬ",
  "SƏFƏR": "ПОЕЗДКА",
  "ƏLAQƏ": "КОНТАКТ",
  "GÜNLÜK TARİF": "ДНЕВНОЙ ТАРИФ",
  "TƏXMİNİ MƏBLƏĞ": "ПРИМЕРНАЯ СУММА",
  "SORĞUNU TAMAMLA": "ЗАВЕРШИТЬ ЗАЯВКУ",
  "WhatsApp ilə göndər": "Отправить через WhatsApp",
  "Məlumatları dəyiş": "Изменить данные",
  "Sorğunuz": "Ваш запрос",
  "hazırdır.": "готов.",
  "WhatsApp-ı yenidən aç": "Открыть WhatsApp снова",
  "CANLI XÜLASƏ": "ЖИВОЕ РЕЗЮМЕ",
  "Müddət": "Срок",
  "Günlük tarif": "Дневной тариф",
  "Təxmini məbləğ": "Примерная сумма",
  "Aydın proses": "Понятный процесс",
  "Göndərmə ödəniş demək deyil": "Отправка не является оплатой",
  "Birbaşa komanda": "Прямая команда",
  "Qiymət seçilmiş müddətə görə hesablanır": "Цена рассчитывается по выбранному сроку"
  ,
  "Yolu daha rahat": "Делаем дорогу",
  "edirik.": "комфортнее.",
  "Müasir avtomobil icarəsi xidməti — həvəskarlar və peşəkarlar üçün.": "Современный сервис аренды автомобилей для любителей и профессионалов.",
  "Carbon Rent A Car sürətli, etibarlı və rahat avtomobil kirayəsi xidmətidir. Müştərilərimizə hər zaman saz, təmiz və sığortalı avtomobillər təqdim edirik.": "Carbon Rent A Car - быстрый, надежный и удобный сервис аренды автомобилей. Мы всегда предоставляем исправные, чистые и застрахованные автомобили.",
  "Komfortlu səyahət,": "Комфортная поездка,",
  "etibarlı xidmət.": "надежный сервис.",
  "Məqsədimiz sizə problemsiz, təhlükəsiz və yüksək keyfiyyətli xidmət göstərməkdir.": "Наша цель - предоставить вам безопасный, качественный и беспроблемный сервис.",
  "Tam sığortalı avtomobillər": "Полностью застрахованные автомобили",
  "CARBON RƏQƏMLƏRLƏ": "CARBON В ЦИФРАХ",
  "BİZİM MİSSİYAMIZ": "НАША МИССИЯ",
  "Rahatlıq.": "Комфорт.",
  "Təhlükəsizlik.": "Безопасность.",
  "Etibar.": "Доверие.",
  "Müştərilərimizə təhlükəsiz, rahat və şəffaf avtomobil kirayəsi xidməti təqdim edərək onların səyahətlərini daha rahat, problemsiz və etibarlı etməyi hədəfləyirik.": "Мы стремимся сделать поездки клиентов комфортнее, проще и надежнее, предоставляя безопасный, удобный и прозрачный сервис аренды автомобилей.",
  "“Sizin yolunuzu rahatlıq və etibar ilə təmin edirik.”": "«Мы обеспечиваем вашу дорогу комфортом и доверием».",
  "CARBON HƏKAYƏSİ": "ИСТОРИЯ CARBON",
  "BİZİ DAHA YAXINDAN TANIYIN": "УЗНАЙТЕ НАС БЛИЖЕ",
  "komandasından.": "команды.",
  "Xidmət yanaşmamızı, müştəri təcrübəsinə baxışımızı və Carbon-un arxasındakı insanları üç qısa videoda izləyin.": "Посмотрите наш подход к сервису, взгляд на клиентский опыт и людей за Carbon в трех коротких видео.",
  "DƏYƏRLƏRİMİZ": "НАШИ ЦЕННОСТИ",
  "Bizim üçün": "Для нас",
  "standart budur.": "это стандарт.",
  "Carbon Rent A Car olaraq məqsədimiz hər bir müştəriyə etibarlı, rahat və problemsiz icarə təcrübəsi təqdim etməkdir.": "Цель Carbon Rent A Car - дать каждому клиенту надежный, удобный и беспроблемный опыт аренды.",
  "Etibar": "Доверие",
  "Hər icarə prosesində açıq kommunikasiya, təhlükəsiz xidmət və məsuliyyətli yanaşma.": "Открытая коммуникация, безопасный сервис и ответственный подход в каждом процессе аренды.",
  "Hər detalı sizin rahatlığınız və problemsiz təcrübəniz üçün düşünürük.": "Мы продумываем каждую деталь для вашего комфорта и беспроблемного опыта.",
  "NİYƏ MƏHZ BİZ?": "ПОЧЕМУ ИМЕННО МЫ?",
  "Siz seçin.": "Вы выбираете.",
  "Qalanını biz həll edək.": "Остальное мы решим.",
  "Tam kasko sığorta": "Полное КАСКО",
  "Depozit qaytarılmasına zəmanət": "Гарантия возврата депозита",
  "24/7 texniki dəstək": "Техническая поддержка 24/7",
  "Dəstək": "Поддержка",
  "Şəffaf proses": "Прозрачный процесс",
  "AKTİV": "АКТИВНО",
  "Müştəriyönümlü yanaşma": "Клиентоориентированный подход",
  "Hər icarə mərhələsində rahatlığınızı və məmnuniyyətinizi əsas götürürük.": "На каждом этапе аренды мы ставим ваш комфорт и удовлетворенность в центр.",
  "HƏR MƏRHƏLƏDƏ YANINIZDA": "РЯДОМ НА КАЖДОМ ЭТАПЕ",
  "Müasir həllər": "Современные решения",
  "Asan rezervasiya, şəffaf qiymətlər və 24/7 dəstək ilə yolunuzda yanınızdayıq.": "Мы рядом с вами благодаря удобному бронированию, прозрачным ценам и поддержке 24/7.",
  "SÜRƏTLİ · SADƏ · ŞƏFFAF": "БЫСТРО · ПРОСТО · ПРОЗРАЧНО",
  "Rahatlıq standart deyil.": "Комфорт - не просто стандарт.",
  "Bizim standartımızdır.": "Это наш стандарт.",
  "OFİSİMİZ": "НАШ ОФИС",
  "BAKI · AZƏRBAYCAN": "БАКУ · АЗЕРБАЙДЖАН",
  "Gəlin": "Приходите",
  "tanış olaq.": "познакомиться.",
  "TELEFON": "ТЕЛЕФОН",
  "Carbon mərkəzi": "Центр Carbon",
  "MARŞRUTU AÇ": "ОТКРЫТЬ МАРШРУТ",
  "Google Maps-də aç": "Открыть в Google Maps",
  "OFİS AKTİVDİR": "ОФИС АКТИВЕН",
  "ƏLƏSGƏR QAYIBOV 12/22": "АЛЕСКЕР ГАИБОВ 12/22",
  "Avtomobil hazırdır.": "Автомобиль готов.",
  "Siz tarixi seçin.": "Выберите даты.",
  "Tarixləri seçin və təxmini qiyməti dərhal görün. Son təsdiqdən əvvəl komandamız mövcudluğu və bütün şərtləri sizinlə dəqiqləşdirəcək.": "Выберите даты и сразу увидите примерную цену. Перед финальным подтверждением команда уточнит наличие и все условия.",
  "Aydın şərtlər": "Понятные условия",
  "Gizli addım yoxdur": "Без скрытых шагов",
  "Birbaşa dəstək": "Прямая поддержка",
  "Carbon komandası ilə": "С командой Carbon",
  "Ödənişsiz sorğu": "Бесплатная заявка",
  "Əvvəl təsdiq, sonra proses": "Сначала подтверждение, затем процесс",
  "Rezervasiyanı təsdiqlə": "Подтвердить бронирование",
  "Sorğu göndərmə ödəniş yaratmır. Mövcudluq və yekun şərtlər Carbon komandası tərəfindən təsdiqlənir.": "Отправка заявки не создает оплату. Наличие и финальные условия подтверждает команда Carbon.",
  "Avtomobil hazırdır": "Автомобиль готов",
  "Siz tarixi seçin": "Выберите даты",
  "Səfərinizi qurun.": "Настройте поездку.",
  "Sorğu açıqdır": "Заявка открыта",
  "Seçilmiş müddət üçün": "За выбранный период",
  "Əlavələr": "Дополнительно",
  "İstəyə bağlı": "Опционально",
  "seçilib": "выбрано"
};

const maps: Record<Locale, Record<string, string>> = {en, ru};
const azPattern = /[ƏəĞğİıÖöŞşÜüÇç]/;

function normalize(value: string) {
  return value.replace(/\s+/g, " ").trim();
}

function translate(value: string, locale: Locale) {
  const map = maps[locale];
  const normalized = normalize(value);
  const exact = map[normalized];

  if (exact) {
    const leading = value.match(/^\s*/)?.[0] ?? "";
    const trailing = value.match(/\s*$/)?.[0] ?? "";
    return `${leading}${exact}${trailing}`;
  }

  if (!azPattern.test(value)) return value;

  let output = value;
  const entries = Object.entries(map).sort((a, b) => b[0].length - a[0].length);

  for (const [source, target] of entries) {
    if (source.length < 4 || !output.includes(source)) continue;
    output = output.split(source).join(target);
  }

  return output;
}

function translateNode(root: ParentNode, locale: Locale) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const textNodes: Text[] = [];

  while (walker.nextNode()) {
    const node = walker.currentNode as Text;
    const parent = node.parentElement;
    if (!parent) continue;
    if (["SCRIPT", "STYLE", "NOSCRIPT"].includes(parent.tagName)) continue;
    if (!normalize(node.nodeValue ?? "")) continue;
    textNodes.push(node);
  }

  for (const node of textNodes) {
    const current = node.nodeValue ?? "";
    const next = translate(current, locale);
    if (next !== current) node.nodeValue = next;
  }

  const elements = root instanceof Element
    ? [root, ...Array.from(root.querySelectorAll<HTMLElement>("input, textarea, button, a, [aria-label], [title]"))]
    : Array.from(root.querySelectorAll<HTMLElement>("input, textarea, button, a, [aria-label], [title]"));

  for (const element of elements) {
    for (const attr of ["placeholder", "aria-label", "title"]) {
      const value = element.getAttribute(attr);
      if (!value) continue;
      const next = translate(value, locale);
      if (next !== value) element.setAttribute(attr, next);
    }
  }
}

export default function CarbonAutoTranslator() {
  const {locale} = useCarbonLanguage();

  useEffect(() => {
    if (locale === "az") return;
    if (window.location.pathname.startsWith("/rezervasiya")) return;

    let scheduled = false;
    const run = () => {
      scheduled = false;
      translateNode(document.body, locale);
    };

    run();

    const observer = new MutationObserver(() => {
      if (scheduled) return;
      scheduled = true;
      window.requestAnimationFrame(run);
    });

    observer.observe(document.body, {
      childList: true,
      subtree: true,
      characterData: true,
      attributes: true,
      attributeFilter: ["placeholder", "aria-label", "title"],
    });

    return () => observer.disconnect();
  }, [locale]);

  return null;
}
