import type { ElementType, SVGProps } from "react";
import {
  AcuraIcon,
  AcuraIconDark,
  AlfaRomeoIcon,
  AlfaRomeoIconDark,
  AstonMartinIcon,
  AstonMartinIconDark,
  AudiIcon,
  AudiIconDark,
  BMWIcon,
  BMWIconDark,
  BYDIcon,
  BYDIconDark,
  BentleyIcon,
  BentleyIconDark,
  BugattiIcon,
  BugattiIconDark,
  BuickIcon,
  BuickIconDark,
  CadillacIcon,
  CadillacIconDark,
  ChevroletIcon,
  ChevroletIconDark,
  ChryslerIcon,
  ChryslerIconDark,
  DodgeIcon,
  DodgeIconDark,
  FerrariIcon,
  FerrariIconDark,
  FiatIcon,
  FiatIconDark,
  FordIcon,
  FordIconDark,
  GMCIcon,
  GMCIconDark,
  GenesisIcon,
  GenesisIconDark,
  HondaIcon,
  HondaIconDark,
  HummerIcon,
  HummerIconDark,
  HyundaiIcon,
  HyundaiIconDark,
  InfinitiIcon,
  InfinitiIconDark,
  JaguarIcon,
  JaguarIconDark,
  JeepIcon,
  JeepIconDark,
  KiaIcon,
  KiaIconDark,
  KoenigseggIcon,
  KoenigseggIconDark,
  LamborghiniIcon,
  LamborghiniIconDark,
  LandroverIcon,
  LandroverIconDark,
  LexusIcon,
  LexusIconDark,
  LincolnIcon,
  LincolnIconDark,
  LotusIcon,
  LotusIconDark,
  LucidIcon,
  LucidIconDark,
  MBIcon,
  MBIconDark,
  MaseratiIcon,
  MaseratiIconDark,
  MazdaIcon,
  MazdaIconDark,
  MclarenIcon,
  MclarenIconDark,
  MiniIcon,
  MiniIconDark,
  MitsubishiIcon,
  MitsubishiIconDark,
  NissanIcon,
  NissanIconDark,
  PaganiIcon,
  PaganiIconDark,
  PolestarIcon,
  PolestarIconDark,
  PorscheIcon,
  PorscheIconDark,
  RAMIcon,
  RAMIconDark,
  RivianIcon,
  RivianIconDark,
  RollsRoyceIcon,
  RollsRoyceIconDark,
  SubaruIcon,
  SubaruIconDark,
  TeslaIcon,
  TeslaIconDark,
  ToyotaIcon,
  ToyotaIconDark,
  VinfastIcon,
  VinfastIconDark,
  VolkswagenIcon,
  VolkswagenIconDark,
  VolvoIcon,
  VolvoIconDark,
} from "@cardog-icons/react";

type LogoComponent = ElementType<SVGProps<SVGSVGElement>>;
type LogoPair = {
  light: LogoComponent;
  dark: LogoComponent;
};

function normalizeBrand(brand?: string | null) {
  return (brand ?? "")
    .normalize("NFKD")
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "");
}

const brandAliases: Record<string, string> = {
  acura: "Acura",
  alfaromeo: "Alfa Romeo",
  astonmartin: "Aston Martin",
  audi: "Audi",
  bmw: "BMW",
  bentley: "Bentley",
  bugatti: "Bugatti",
  buick: "Buick",
  byd: "BYD",
  cadillac: "Cadillac",
  chevrolet: "Chevrolet",
  chevy: "Chevrolet",
  chrysler: "Chrysler",
  dodge: "Dodge",
  ferrari: "Ferrari",
  fiat: "Fiat",
  ford: "Ford",
  genesis: "Genesis",
  gmc: "GMC",
  honda: "Honda",
  hummer: "Hummer",
  hyundai: "Hyundai",
  infiniti: "Infiniti",
  infinity: "Infiniti",
  jaguar: "Jaguar",
  jeep: "Jeep",
  kia: "Kia",
  koenigsegg: "Koenigsegg",
  lamborghini: "Lamborghini",
  landrover: "Land Rover",
  rangerover: "Land Rover",
  lexus: "Lexus",
  lincoln: "Lincoln",
  lotus: "Lotus",
  lucid: "Lucid",
  maserati: "Maserati",
  mazda: "Mazda",
  mclaren: "McLaren",
  maclaren: "McLaren",
  mercedes: "Mercedes-Benz",
  mercedesbenz: "Mercedes-Benz",
  mercedesben: "Mercedes-Benz",
  mercedesbenzamg: "Mercedes-Benz",
  mb: "Mercedes-Benz",
  mini: "Mini",
  mitsubishi: "Mitsubishi",
  nissan: "Nissan",
  pagani: "Pagani",
  polestar: "Polestar",
  porsche: "Porsche",
  ram: "RAM",
  rivian: "Rivian",
  rollsroyce: "Rolls-Royce",
  subaru: "Subaru",
  tesla: "Tesla",
  toyota: "Toyota",
  vinfast: "VinFast",
  volkswagen: "Volkswagen",
  vw: "Volkswagen",
  volvo: "Volvo",
};

const brandLogos: Record<string, LogoPair> = {
  Acura: { light: AcuraIcon, dark: AcuraIconDark },
  "Alfa Romeo": { light: AlfaRomeoIcon, dark: AlfaRomeoIconDark },
  "Aston Martin": { light: AstonMartinIcon, dark: AstonMartinIconDark },
  Audi: { light: AudiIcon, dark: AudiIconDark },
  BMW: { light: BMWIcon, dark: BMWIconDark },
  Bentley: { light: BentleyIcon, dark: BentleyIconDark },
  Bugatti: { light: BugattiIcon, dark: BugattiIconDark },
  Buick: { light: BuickIcon, dark: BuickIconDark },
  BYD: { light: BYDIcon, dark: BYDIconDark },
  Cadillac: { light: CadillacIcon, dark: CadillacIconDark },
  Chevrolet: { light: ChevroletIcon, dark: ChevroletIconDark },
  Chrysler: { light: ChryslerIcon, dark: ChryslerIconDark },
  Dodge: { light: DodgeIcon, dark: DodgeIconDark },
  Ferrari: { light: FerrariIcon, dark: FerrariIconDark },
  Fiat: { light: FiatIcon, dark: FiatIconDark },
  Ford: { light: FordIcon, dark: FordIconDark },
  Genesis: { light: GenesisIcon, dark: GenesisIconDark },
  GMC: { light: GMCIcon, dark: GMCIconDark },
  Honda: { light: HondaIcon, dark: HondaIconDark },
  Hummer: { light: HummerIcon, dark: HummerIconDark },
  Hyundai: { light: HyundaiIcon, dark: HyundaiIconDark },
  Infiniti: { light: InfinitiIcon, dark: InfinitiIconDark },
  Jaguar: { light: JaguarIcon, dark: JaguarIconDark },
  Jeep: { light: JeepIcon, dark: JeepIconDark },
  Kia: { light: KiaIcon, dark: KiaIconDark },
  Koenigsegg: { light: KoenigseggIcon, dark: KoenigseggIconDark },
  Lamborghini: { light: LamborghiniIcon, dark: LamborghiniIconDark },
  "Land Rover": { light: LandroverIcon, dark: LandroverIconDark },
  Lexus: { light: LexusIcon, dark: LexusIconDark },
  Lincoln: { light: LincolnIcon, dark: LincolnIconDark },
  Lotus: { light: LotusIcon, dark: LotusIconDark },
  Lucid: { light: LucidIcon, dark: LucidIconDark },
  Maserati: { light: MaseratiIcon, dark: MaseratiIconDark },
  Mazda: { light: MazdaIcon, dark: MazdaIconDark },
  McLaren: { light: MclarenIcon, dark: MclarenIconDark },
  "Mercedes-Benz": { light: MBIcon, dark: MBIconDark },
  Mini: { light: MiniIcon, dark: MiniIconDark },
  Mitsubishi: { light: MitsubishiIcon, dark: MitsubishiIconDark },
  Nissan: { light: NissanIcon, dark: NissanIconDark },
  Pagani: { light: PaganiIcon, dark: PaganiIconDark },
  Polestar: { light: PolestarIcon, dark: PolestarIconDark },
  Porsche: { light: PorscheIcon, dark: PorscheIconDark },
  RAM: { light: RAMIcon, dark: RAMIconDark },
  Rivian: { light: RivianIcon, dark: RivianIconDark },
  "Rolls-Royce": { light: RollsRoyceIcon, dark: RollsRoyceIconDark },
  Subaru: { light: SubaruIcon, dark: SubaruIconDark },
  Tesla: { light: TeslaIcon, dark: TeslaIconDark },
  Toyota: { light: ToyotaIcon, dark: ToyotaIconDark },
  VinFast: { light: VinfastIcon, dark: VinfastIconDark },
  Volkswagen: { light: VolkswagenIcon, dark: VolkswagenIconDark },
  Volvo: { light: VolvoIcon, dark: VolvoIconDark },
};

export function CarBrandLogo({
  brand,
  size = 28,
  tone = "light",
}: {
  brand?: string | null;
  size?: number;
  tone?: "light" | "dark";
}) {
  const canonical = brandAliases[normalizeBrand(brand)];
  const logo = canonical ? brandLogos[canonical] : null;
  const Logo = logo?.[tone] ?? logo?.light;

  if (Logo) {
    return <Logo width={size} height={size} aria-label={`${canonical} loqosu`} />;
  }

  return <strong aria-label={`${brand ?? "Brend"} loqosu`}>{(brand ?? "C").slice(0, 2).toUpperCase()}</strong>;
}
